# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_search.setInputMask("")
        self.lineEdit_search.setText("")
        self.lineEdit_search.setMaxLength(25)
        self.lineEdit_search.setCursorPosition(0)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.comboBox_ressource = QtWidgets.QComboBox(self.frame)
        self.comboBox_ressource.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_ressource.setObjectName("comboBox_ressource")
        self.horizontalLayout.addWidget(self.comboBox_ressource)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableView_planning = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_planning.sizePolicy().hasHeightForWidth())
        self.tableView_planning.setSizePolicy(sizePolicy)
        self.tableView_planning.setMaximumSize(QtCore.QSize(1000000, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableView_planning.setFont(font)
        self.tableView_planning.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.tableView_planning.setProperty("showDropIndicator", False)
        self.tableView_planning.setDragDropOverwriteMode(False)
        self.tableView_planning.setObjectName("tableView_planning")
        self.tableView_planning.horizontalHeader().setDefaultSectionSize(24)
        self.tableView_planning.horizontalHeader().setMinimumSectionSize(24)
        self.tableView_planning.verticalHeader().setDefaultSectionSize(24)
        self.tableView_planning.verticalHeader().setMinimumSectionSize(24)
        self.gridLayout.addWidget(self.tableView_planning, 0, 1, 1, 1)
        self.treeView_projects = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_projects.setMaximumSize(QtCore.QSize(300, 16777215))
        self.treeView_projects.setStyleSheet("")
        self.treeView_projects.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView_projects.setObjectName("treeView_projects")
        self.treeView_projects.header().setDefaultSectionSize(24)
        self.treeView_projects.header().setMinimumSectionSize(24)
        self.gridLayout.addWidget(self.treeView_projects, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuProjects = QtWidgets.QMenu(self.menubar)
        self.menuProjects.setObjectName("menuProjects")
        self.menuTasks = QtWidgets.QMenu(self.menubar)
        self.menuTasks.setObjectName("menuTasks")
        self.menuAcitivty = QtWidgets.QMenu(self.menubar)
        self.menuAcitivty.setObjectName("menuAcitivty")
        self.menuParameters = QtWidgets.QMenu(self.menubar)
        self.menuParameters.setObjectName("menuParameters")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionToday = QtWidgets.QAction(MainWindow)
        self.actionToday.setObjectName("actionToday")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionEdit_Projects = QtWidgets.QAction(MainWindow)
        self.actionEdit_Projects.setObjectName("actionEdit_Projects")
        self.actionNew_task = QtWidgets.QAction(MainWindow)
        self.actionNew_task.setObjectName("actionNew_task")
        self.actionEdit_task = QtWidgets.QAction(MainWindow)
        self.actionEdit_task.setObjectName("actionEdit_task")
        self.actionNew_Activity = QtWidgets.QAction(MainWindow)
        self.actionNew_Activity.setObjectName("actionNew_Activity")
        self.actionEdit_Activity = QtWidgets.QAction(MainWindow)
        self.actionEdit_Activity.setObjectName("actionEdit_Activity")
        self.actionRessources = QtWidgets.QAction(MainWindow)
        self.actionRessources.setObjectName("actionRessources")
        self.actionAcitivty_Types = QtWidgets.QAction(MainWindow)
        self.actionAcitivty_Types.setObjectName("actionAcitivty_Types")
        self.menuFichier.addAction(self.actionNew)
        self.menuFichier.addAction(self.actionOpen)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionExit)
        self.menuProjects.addAction(self.actionNew_Project)
        self.menuProjects.addAction(self.actionEdit_Projects)
        self.menuTasks.addAction(self.actionNew_task)
        self.menuTasks.addAction(self.actionEdit_task)
        self.menuAcitivty.addAction(self.actionNew_Activity)
        self.menuAcitivty.addAction(self.actionEdit_Activity)
        self.menuParameters.addAction(self.actionRessources)
        self.menuParameters.addAction(self.actionAcitivty_Types)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuProjects.menuAction())
        self.menubar.addAction(self.menuTasks.menuAction())
        self.menubar.addAction(self.menuAcitivty.menuAction())
        self.menubar.addAction(self.menuParameters.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionToday)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.treeView_projects.clicked['QModelIndex'].connect(self.tableView_planning.update)
        self.lineEdit_search.textChanged['QString'].connect(MainWindow.searchTask)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "Search Task"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuProjects.setTitle(_translate("MainWindow", "Projects"))
        self.menuTasks.setTitle(_translate("MainWindow", "Tasks"))
        self.menuAcitivty.setTitle(_translate("MainWindow", "Activity"))
        self.menuParameters.setTitle(_translate("MainWindow", "Parameters"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionToday.setText(_translate("MainWindow", "Today"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project..."))
        self.actionEdit_Projects.setText(_translate("MainWindow", "Edit Projects..."))
        self.actionNew_task.setText(_translate("MainWindow", "New task..."))
        self.actionEdit_task.setText(_translate("MainWindow", "Edit task..."))
        self.actionNew_Activity.setText(_translate("MainWindow", "New Activity..."))
        self.actionEdit_Activity.setText(_translate("MainWindow", "Edit Activity..."))
        self.actionRessources.setText(_translate("MainWindow", "Ressources..."))
        self.actionAcitivty_Types.setText(_translate("MainWindow", "Acitivty Types..."))

